### ISSUE TITLE
Upgrading Ghost

### ISSUE THREAD

**Issue by thomcrowe** [cobyism/ghost-on-heroku#104]
I deployed this and have a notification in my Ghost settings to upgrade to 0.11.7 but I can't seem to find out how to do it. Do you have any suggestions?

Thanks

**Comment by liberaltech** [comment]
I recently updated to `0.11.7` using [npm-check-updates](https://github.com/tjunnone/npm-check-updates).

> npm-check-updates is a command-line tool that allows you to upgrade your package.json or bower.json dependencies to the latest versions, regardless of existing version constraints.
Make sure you back up your data and run tests before you deploy.

Install `npm-check-updates` globally
```
npm i -g npm-check-updates
```
Check dependencies
```
ncu
```
Upgrade **Ghost** to `0.11.7`
```
ncu -u ghost@0.11.7
```
Update `engines` in `package.json` to `"node": "^4.2.0 || ^6.9.0"`
```json
"engines": {
    "node": "^4.2.0 || ^6.9.0"
  }
```
Update `"version"` in `package.json`
```json
"version": "0.11.7"
```

**Comment by briandwendt** [comment]
Is there an approved method for upgrading Ghost when using `ghost-on-heroku`?  I cloned locally and successfully added themes, made style updates, etc., but using the above method to force an upgrade to **Ghost v1.20.0** resulted in Heroku application errors, likely resulting from my failure to migrate the JawsDB as well.  Is there a way to do this using `knex` or some other tool?

**Comment by briandwendt** [comment]
**Solved.**  Per #119, I added the following line to my `Procfile`:
    release: knex-migrator migrate --mgpath node_modules/ghost

Now the Heroku release process runs on every deployment, upgrading Ghost version and performing database migrations if required.

**Comment by mars** [comment]
Added docs for [ghost-on-heroku upgrades & migrations](https://github.com/cobyism/ghost-on-heroku/blob/master/README.md#user-content-upgrading-ghost).
