### ISSUE TITLE
Getting the content of my current blog hosted on heroku

### ISSUE THREAD

**Issue by lpolaright** [cobyism/ghost-on-heroku#108]
After following the instructions in the README.md:

> Updating
> 
> After deploying your own Ghost blog, you can update it by running the following commands:
> 
> heroku git:clone --app YOURAPPNAME && cd YOURAPPNAME
> git remote add origin https://github.com/cobyism/ghost-on-heroku
> git pull origin master # may trigger a few merge conflicts, depending on how long since last update
> git push heroku master
> This will pull down the code that was deployed to Heroku so you have it locally, attach this repository as a new remote, attempt to pull down the latest version and merge it in, and then push that change back to your Heroku app instance.

I have a git repository but with none of the current posts in heroku.
I tried git pull origin master but it says I'm up-to-date.

What am I missing? I've searched all the folders in the repo.

**Comment by ifvictr** [comment]
@lpolaright Your blog data is hosted in a PostgreSQL database and not in the local filesystem.

**Comment by mars** [comment]
In the newest versions of this app (Ghost 1.x), the MySQL database is where all posts are stored.

By default, ghost-on-heroku now deploys with a JawsDB hosted MySQL database. JawsDB offers a [database backup](https://devcenter.heroku.com/articles/jawsdb#database-backups) interface to export or import your Ghost blog data.
