### ISSUE TITLE
[Solved] Ghost blog + Bucketeer = Invalid Status Code:0

### ISSUE THREAD

**Issue by mrneilypops** [cobyism/ghost-on-heroku#111]
Hi,
When I try and upload an image in Ghost v.0.11.10 using Bucketeer I get the error;
Invalid Status Code:0
I am able to manually upload to the S3 instance using aws-cli.

Any tips most welcome.
Neil

![screenshot from 2017-07-10 16-16-15](https://user-images.githubusercontent.com/1450448/28029158-659c97c8-659f-11e7-97ea-0347670a2638.png)

neiljune@neiljune-desktop:~$ aws s3 ls s3://bucketeer-a767f5ea-eed5-448f-8907-45d1f1d85928
                           PRE public/
neiljune@neiljune-desktop:~$ curl  https://bucketeer-a767f5ea-eed5-448f-8907-45d1f1d85928.s3.amazonaws.com/public/hello.html
<h1>hello, world</h1>
neiljune@neiljune-desktop:~$ https://bucketeer-a767f5ea-eed5-448f-8907-45d1f1d85928.s3.amazonaws.com/public/
bash: https://bucketeer-a767f5ea-eed5-448f-8907-45d1f1d85928.s3.amazonaws.com/public/: No such file or directory
neiljune@neiljune-desktop:~$ aws s3 ls s3://bucketeer-a767f5ea-eed5-448f-8907-45d1f1d85928
                           PRE public/
neiljune@neiljune-desktop:~$ aws s3 ls s3://bucketeer-a767f5ea-eed5-448f-8907-45d1f1d85928/public/
2017-07-10 18:29:28         22 hello.html
neiljune@neiljune-desktop:~$

**Comment by mrneilypops** [comment]
This is the solution for Ghost v.0.11
https://github.com/cobyism/ghost-on-heroku/issues/83

**Comment by holic** [comment]
Glad you found a solution!
