### ISSUE TITLE
S3_BUCKET_REGION config vars

### ISSUE THREAD

**Issue by mrneilypops** [cobyism/ghost-on-heroku#112]
I had to add S3_BUCKET_REGION to Ghost v0.11.10 in order to enable image uploads with Bucketeer as per;
https://github.com/cobyism/ghost-on-heroku/issues/83

Would it be possible to include this requirement for v.0.11 to cobyism/ghost-on-heroku procedure?
Would it be possible for this requirement to be included in your config?

Keep up the great work!
Neil
![screenshot from 2017-07-11 21-01-45](https://user-images.githubusercontent.com/1450448/28085661-b5ea5e94-667c-11e7-9f7c-0b41b6432d10.png)

**Comment by cobyism** [comment]
Unfortunately, I don’t think it’s possible to have [app.json env variables](https://devcenter.heroku.com/articles/app-json-schema#env) be required, but only if specific other fields are given values. We could mark this as a required variable, but then if someone wanted to use Ghost without using S3 at all it’d get confusing very quickly, so I’d probably rather leave this as optional and rely on the README which [mentions this is a required field](https://github.com/cobyism/ghost-on-heroku#configuring-s3-file-uploads) if using S3.
