### ISSUE TITLE
Cloning the Heroku app repository yields an empty repository

### ISSUE THREAD

**Issue by elis** [cobyism/ghost-on-heroku#126]
After doing the one-click deployment which indeed setup a ghost blog running on heroku doing fine, but when trying to clone the repository (either by using `git clone` or by using the heroku toolbet) I'm receiving an empty repository.

What can be the issue?

**Comment by jozic** [comment]
@elis see this #68

**Comment by elis** [comment]
@jozic Thanks! exactly what I was looking for.
