### ISSUE TITLE
NPM 5.4.x error (Cannot read property 'pause' of undefined)

### ISSUE THREAD

**Issue by jamiegoodwin** [cobyism/ghost-on-heroku#127]
NPM 5.4.x has introduced [a bug](https://github.com/npm/npm/issues/18520), which is blocking the deployment process because Heroku defaults to the latest version of NPM.

This can be fixed by locking NPM 5.3.0 in package.json.

```
"engines": {
    "node": "^4.8.4 || ^6.11.1",
    "npm": "5.3.0"
  },
```

I'm not sure how to do pull requests so I'm just opening an issue so you guys are aware of the issue and how to fix it :-)

**Comment by eduarmreyes** [comment]
Thanks, really helped me on this one

**Comment by cobyism** [comment]
Thanks for the report. If this is affecting everyone, it might be worth opening a PR to add this, however if it’s not going to be a permanent or widespread issue I’d prefer to keep our package.json as aligned as possible with [the TryGhost/ghost one](https://github.com/TryGhost/Ghost/blob/master/package.json) (which doesn’t specify an NPM version).

**Comment by mars** [comment]
Heroku itself implemented an automatic build workaround for this npm version’s bug.
