### ISSUE TITLE
Planning to merge 0.11.12?

### ISSUE THREAD

**Issue by jamiesmith** [cobyism/ghost-on-heroku#128]
Hi- are you planing on merging in 0.11.12?  

I was shocked to see it released a few minutes ago:

https://github.com/TryGhost/Ghost/releases/tag/0.11.12
https://gist.github.com/kirrg001/7a61d9eaeb51beedac220555957a7fdc

Or should I try to fork & PR?  I still see references to postrgres in the code

**Comment by jamiesmith** [comment]
I submitted a PR for this, I didn't realize it was just a package.json thing

**Comment by cobyism** [comment]
I’d love for this repo to have a tag containing the 0.11.12 code, so that people can continue to use that instead of v1.X if they want. 👍

**Comment by mars** [comment]
Here's a [**ghost-0.11.x** branch](https://github.com/cobyism/ghost-on-heroku/tree/ghost-0.11.x) from just before the Ghost 1.x transition.

If folks want to open pull requests against this branch, I'm happy to give them a quick review & merge, but we won't be quality checking or debugging these old LTS releases.
