### ISSUE TITLE
Ghost upgrades confusion

### ISSUE THREAD

**Issue by mrneilypops** [cobyism/ghost-on-heroku#136]
I have been unsuccessful in trying to upgrade my Ghost blog in v1.x
I resort to a complete reinstall from the one click deploy each time.
I would appreciate some pointers as to where I might be going wrong with git.
I have followed the instructions as per;
git clone https://github.com/cobyism/ghost-on-heroku
cd ghost-on-heroku
heroku git:remote -a YOURAPPNAME
heroku info
git add .
git commit -m "Important changes"
git push heroku master

For example, I had Ghost v1.19 installed and I wanted to upgrade to v1.20.
The above does not upgrade Ghost even with a fresh git clone...
Am I missing an important step here?

**Comment by mars** [comment]
Locally, run `npm update`, and then commit the changes that made to **package.json** & **package.lock**.

Deploy that with `git push heroku master`.

Once deployment completes, update the database schema via `heroku run knex-migrator migrate --mgpath node_modules/ghost`.

The whole script should be something like (have not confirmed):

```bash
npm update
# …wait…
git commit . -m 'Update package dependencies'
git push heroku master
# …wait…
heroku run knex-migrator migrate --mgpath node_modules/ghost
# …wait…
heroku restart
```

**Comment by mrneilypops** [comment]
@mars 
Thank you very much for the input...but Ghost is still not showing the upgrade v1.19 to v1.20.

![screenshot from 2018-01-12 15-42-50](https://user-images.githubusercontent.com/1450448/34879984-4e07f862-f7af-11e7-9799-eff50b27be7c.png)

**Comment by mrneilypops** [comment]
@mars
Thanks again but still no success with an upgrade...
I have tried various combinations of commands but still no joy.
As I have very few posts on my blog I have decided to export/import .json files and redeploy the one-click install when a Ghost update is available.
I will monitor for any additional info and also the required Ghost feature of 'one-click update'

Cheers,
Neil

https://mrneilypops.org

![screenshot from 2018-01-12 19-21-27](https://user-images.githubusercontent.com/1450448/34889425-3a36085a-f7ce-11e7-9a69-68791b2aaa39.png)

**Comment by ifvictr** [comment]
@mrneilypops Did you make sure you deployed it after updating the repo?

**Comment by mars** [comment]
ghost-on-heroku is just a Node/Express app with Ghost as a **package.json** dependency.

Upgrades work like any other npm module, plus you may need to run the knex database schema migrations.
