### ISSUE TITLE
S3 file path incorrect when using Bucketeer

### ISSUE THREAD

**Issue by ibigfoot** [cobyism/ghost-on-heroku#137]
After adding bucketeer the file path rendered in the blog is incorrect, it has a host of

https://s3-undefined.amazonaws.com/<bucket_name>/<path to file> 

Is there a config var that needs to be set? If I just use s3.amazonaws.com the file resolves.

**Comment by mars** [comment]
The required config vars are [described in the README](https://github.com/cobyism/ghost-on-heroku#configuring-s3-file-uploads).

**Comment by ibigfoot** [comment]
It is the bucketeer part that doesn't seem to work. "The environment variables set by the add-on will be automatically detected and used to configure your Ghost blog and enable uploads." The uploads work, but displaying on the UI doesn't.

Do I need to manually copy the bucketeer config vars into the S3 config vars described?

**Comment by mars** [comment]
Apparently with Bucketeer one of those config vars, `S3_BUCKET_REGION`, must be set manually for URLs to be correct generated.

I just updated the README to clarify [Provisioning an S3 bucket using an add-on](https://github.com/cobyism/ghost-on-heroku/blob/master/README.md#user-content-provisioning-an-s3-bucket-using-an-add-on).
