### ISSUE TITLE
Images are disappearing

### ISSUE THREAD

**Issue by marekdlugos** [cobyism/ghost-on-heroku#142]
I have deployed Ghost on Heroku free tier and started playing with it. However, it seems that the cover pictures of articles somehow disappear after some time. (Did not really test it how long it takes)

E.g. I write and post an article with a cover picture. When I come back to my blog after 4 days, none of the articles has a picture. When I try to access a picture URL I got: "404 Image not found".

Any ideas how to fix it?

**Comment by ifvictr** [comment]
@marekdlugos Heroku has an ephemeral filesystem--your images are deleted after the dyno goes to sleep. You should store your images on an external provider using a storage adapter like [ghost-imgur](https://github.com/wrenth04/ghost-imgur), [ghost-github](https://github.com/ifvictr/ghost-github), or [ghost-storage-adapter-s3](https://github.com/colinmeinke/ghost-storage-adapter-s3).

**Comment by mars** [comment]
Using Amazon S3 for file storage is documented in the README: https://github.com/cobyism/ghost-on-heroku/blob/master/README.md#user-content-using-with-file-uploads-disabled

The easiest way is with the Bucketeer Add-on. It’s all documented there.

**Comment by marekdlugos** [comment]
Thank you so much, guys! Stupid me, haha.
