### ISSUE TITLE
Theme deleted on a re-deploy

### ISSUE THREAD

**Issue by chinds185a** [cobyism/ghost-on-heroku#143]
Is there a way for us to have persistent storage for a custom ghost theme, my heroku instance may get re-deployed and restarted by the heroku service without my knowing, or the free version of heroku will spin down the instance every 30 minutes.

When the server comes backup the theme is gone due to the lack of persistent storage with heroku, which to me makes this deploy button useless unless you are only going to use the default built in casper theme.

**Comment by ifvictr** [comment]
@chinds185a Just install the theme before you deploy it on Heroku.

**Comment by nicktheo59** [comment]
But would all other data still persist? Pretty sure images after added do not.
The solution is to use an S3 bucket but I'm looking for good instructions on how to do this.
