### ISSUE TITLE
Mail is not working

### ISSUE THREAD

**Issue by maxp-edcast** [cobyism/ghost-on-heroku#144]
Steps to reproduce:

1. Click "deploy to heroku button", configure and launch
2. create admin user
3. try and invite a user by email

Result:

An error occurs, that the email failed to send, and a link to Ghost's docs on email setup.

If some further configuration is required for email other than the default setup when you click "deploy to heroku", I would appreciate if it could be documented.

Otherwise, thanks for this library I think it's great.

**Comment by mars** [comment]
You might need to do some configuration of the Mailgun add-on before it works. Open the app's **Mailgun** Add-on through the Heroku dashboard and ensure that it's setup.
