### ISSUE TITLE
How to get blog data when developing locally?

### ISSUE THREAD

**Issue by alexerhardt** [cobyism/ghost-on-heroku#145]
I've read issue #108 but I still don't understand how we can retrieve the JawsDB data when developing locally.

I've tried exporting the JAWS_DB env variable and running wait-for-db to connect to JAWS_DB. I get a connection successful message, but running server later does not retrieve the data from the remote database.

What am I missing? Is it possible to connect to the remote database at all?

**Comment by mars** [comment]
As mentioned in the [JawsDB database-backup docs](https://devcenter.heroku.com/articles/jawsdb#database-backups), you can use `mysqldump` to export from a remote or local database, and then use `mysql` to import into a different remote or local database.
