### ISSUE TITLE
How to run locally

### ISSUE THREAD

**Issue by bhellman1** [cobyism/ghost-on-heroku#146]
After cloning the repo locally, running `npm install` and then `npm start` I get the following errors:

```
> node server.js

[2018-06-16 00:18:22] ERROR Target log folder does not exist: content/logs/ 
[2018-06-16 00:18:24] ERROR Target log folder does not exist: content/logs/ 
```

Any instructions on how to run this locally?

**Comment by markhillard** [comment]
@bhellman1, I got this same error and just manually created the `logs` folder under `content`. After that I ran the following command in console:

`knex-migrator init --mgpath node_modules/ghost`

It should built out the local db for you... then run `npm start` again and see what happens.
