### ISSUE TITLE
Where does the NGINX config live?

### ISSUE THREAD

**Issue by chinds185a** [cobyism/ghost-on-heroku#147]
This is pre setup with some kind fo server, is it NGINX? No mention of this in the readme.

I need to be able to setup redirects on the server. use the redirects.json within ghost is not recommended and also does not persist due to the non persistant storage on heroku.

**Comment by mars** [comment]
See the README [How this works](https://github.com/cobyism/ghost-on-heroku/blob/master/README.md#user-content-how-this-works)

`server.js` is a simple Node/Express app. Modify it as you desire.
