### ISSUE TITLE
Uploaded theme gets deleted when Dyno is restarted

### ISSUE THREAD

**Issue by ov3rkill** [cobyism/ghost-on-heroku#154]
Hello,

Everytime a dyno is restarted, the theme files go missing, and have to be reuploaded again manually.

**Comment by mars** [comment]
For Heroku deployments, filesystem changes must be committed to git and deployed. See the README [Updating the source code](https://github.com/cobyism/ghost-on-heroku/blob/master/README.md#updating-source-code).
