### ISSUE TITLE
Adding Disqus comments to existing heroku ghost app

### ISSUE THREAD

**Issue by karthikchintala1** [cobyism/ghost-on-heroku#155]
I've installed ghost through cobysium on heroku.com. Thank you.

But as I cloned the repo I just don't get all the source code I just got the .git folder and it the terminal says

> warning: You appear to have cloned an empty repository.

So, I only have .git folder in the cloned repo. 

How to setup Disqus comments on the existing heroku app?

I tried by connecting the heroku to github.com to a repo but I can't build the ghost repo successfully. So, I disconnected the github repo from heroku.

**Comment by mars** [comment]
The README describes how to [get the source code](https://github.com/cobyism/ghost-on-heroku/blob/master/README.md#updating-source-code).

I don’t have any personal knowledge of Discus, though.

**Comment by karthikchintala1** [comment]
@mars Thanks for the response.

I tried by downloading that but no use of downloading the code as it doesn't have any files to configure Disqus.

I found a way to adjust the comments section through `code injection` in ghost blog.

https://gist.github.com/novaugust/aa73f696a72f2a2dacce85c424e12558.

Closing the issue.
