### ISSUE TITLE
Cloudinary Storage

### ISSUE THREAD

**Issue by i-mighty** [cobyism/ghost-on-heroku#161]
I have tried to use cloudinary storage to a blog on heroku using this repo.
Any ideas or suggestions would be welcomed.

**Comment by mars** [comment]
I cannot think of a reason that Cloudinary would not work with ghost-on-heroku.

You'll probably need to follow a guide like [this one](https://ryanerickson.com/host-your-ghost-blog-images-on-cloudinary/).

You can change your Ghost blog's configuration in [`bin/create-config`](https://github.com/cobyism/ghost-on-heroku/blob/master/bin/create-config), which generates the production JSON config file at runtime.
