### ISSUE TITLE
Suggested way to update?

### ISSUE THREAD

**Issue by schniggie** [cobyism/ghost-on-heroku#17]
Hey,

I installed ghost some month ago on heroku with your one-click installer and still using 0.5.8. What is the suggested / easiest way to update to the latest Version? Maybe you could also add that description to the Readme.

**Comment by cobyism** [comment]
@schniggie Yep, good point—thanks for opening an issue. Off the top of my head, I imagine the sequence would need to be something along the lines of the following:

```
heroku clone --app YOURAPPNAME && cd YOURAPPNAME
git remote add origin https://github.com/cobyism/ghost-on-heroku
git pull origin master # may trigger a few merge conflicts, depending on how old the version is?
git push heroku master
```

Basically what those commands do is pull down the code that was deployed to heroku so you have it locally, attach this repository as a new remote, attempt to pull down the latest version and merge it in, and the push that change back to your heroku app instance. Do you want to give that a try and see if that works for you?

**Comment by NelsonScott** [comment]
This worked for me, @cobyism do you think this info should be added to the readme? I imagine other people will eventually want to do the same.

**Comment by cobyism** [comment]
@NelsonScott Yeah, if that works as a way to upgrade, adding it to the readme would be :sparkles:. Was there anything else you had to do outside of that as part of the upgrade? Care to take a stab at a pull request to add it to the readme?

**Comment by NelsonScott** [comment]
@cobyism it worked for me, no problems
pr: https://github.com/cobyism/ghost-on-heroku/pull/40

**Comment by cobyism** [comment]
@NelsonScott Thanks a ton for that PR!
