### ISSUE TITLE
FYI: GMail instead of Mandrill

### ISSUE THREAD

**Issue by dai-shi** [cobyism/ghost-on-heroku#25]
I would like to let you know that I tried my fork to support GMail instead of Mandrill for SMTP transport.
Thanks.
https://github.com/dai-shi/ghost-on-heroku

**Comment by cobyism** [comment]
@dai-shi :+1: Thanks for letting me know. The Mandrill addon this comes with at present used to provide a free tier, but it looks like that changed. If you have thoughts about what we should do instead, I’d love to hear your thoughts in #26. :grin:

**Comment by dai-shi** [comment]
@cobyism What a timing. Sure, I will follow #26.
