### ISSUE TITLE
Replace Mandrill with Mailgun

### ISSUE THREAD

**Issue by holic** [cobyism/ghost-on-heroku#26]
Mailgun has a free tier and might be better for trialling Ghost on Heroku without a cost commitment.

**Comment by cobyism** [comment]
Thanks for opening this issue. Mandrill used to offer a free tier, but it looks like that’s no longer the case (or perhaps it was never the case, and I’m going mad :stuck_out_tongue_winking_eye: ). If this was a recent change, that might explain the reasoning behind https://github.com/cobyism/ghost-on-heroku/issues/25.

Anyway… yes—we should absolutely switch this over to use a mail provider with a free tier.

@holic I’ve made you a collaborator on this repo. Do you feel like having a go at changing this over to using either [Mailgun](https://elements.heroku.com/addons/mailgun) or [SendGrid](https://elements.heroku.com/addons/sendgrid)?

**Comment by holic** [comment]
I certainly can do that and was intending to, I just hadn't got around to it. Added this issue as a note-to-self.

**Comment by cobyism** [comment]
@holic :metal: :sparkles:

**Comment by dai-shi** [comment]
As you guess, that was the reason for #25. I'm totally fine with other free SMTP services.

**Comment by cobyism** [comment]
@dai-shi Thanks for the clarification, good to know. :+1:

**Comment by Dorgam** [comment]
How much is this going to take?
Thank you guys.
