### ISSUE TITLE
How do I install a custom theme?

### ISSUE THREAD

**Issue by kandadaboggu** [cobyism/ghost-on-heroku#28]
I am wondering how I can install a custom theme.

**Comment by holic** [comment]
1. Clone your Ghost repo from Heroku, e.g. `heroku clone --app YOUR_APP_NAME`
2. Clone the theme repo (or copy+paste the directory) into `content/themes/`
3. Commit the files to the Ghost repo
4. Push new commit to Heroku
5. Select the new theme from within your Ghost settings (under `yourappname.herokuapp.com/ghost/settings/`)
6. Restart Ghost with `heroku restart` (not sure if this is still required)

**Comment by Superjd10** [comment]
I did clone the Github repo and then installed Ghost in Heroku using my own repo. Enabled automatic deploys from Github (personal preference), and edit whatever I need directly from Github. That will do everything (push the commits, restart the heroku app deploying it), and then like mentioned above, select the new theme in your Ghost settings.

**Comment by cobyism** [comment]
I’m going to close this out, but it’d be great to have instructions for installing a theme to a Heroku-hosted Ghost blog in the README. Anyone have enough spare cycles to open a PR to add some instructions along the lines of @holic’s comment above?

**Comment by aadimator** [comment]
@holic Nice tips. Just one thing, when I clone my custom Github theme repo inside /contents/theme/ directory, and try to add it to the heroku repo, it gives the following error. 
![image](https://user-images.githubusercontent.com/10383542/35429585-795e3d22-0296-11e8-8edc-d1f07f0d81fa.png)

Is there a way to integrate my Github theme repo in such a way that whenever I update the theme on Github, heroku automatically uses the new one without me having to manually copy and paste the new theme in to the folder and pushing it again and again?
