### ISSUE TITLE
Problem Adding to Custom Domain

### ISSUE THREAD

**Issue by NelsonScott** [cobyism/ghost-on-heroku#37]
First, just want to say this script to get up and running on heroku with Ghost works great, thanks for making it so easy.  

The issue I'm having now is configuring my DNS to add my blog to a custom subdomain.  It seems that adding a Custom Resource Record CNAME, supplying it with the heroku url, and then navigating to the subdomain results in the browser forwarding to the url of the app hosted on heroku.  This behavior doesn't seem to happen for other apps hosted on heroku that I have successfully added to subdomains on my custom domain and seem to be integrated properly (I'm using Google Domains to manage DNS).  

I was wondering if anyone was able to successfully add a custom sub-domain (NOT just subdomain forwarding) for your Ghost app hosted on heroku, or if this is a known issue.

**Comment by cobyism** [comment]
Other than following the [regular instructions](https://devcenter.heroku.com/articles/custom-domains) on the Heroku side of things, the other thing you might need to do is adjust the `HEROKU_URL` environment variable to be your custom domain instead of `https://YOURAPPNAME.herokuapp.com`, so that Ghost itself uses the correct root URL when creating links between all the pages. Could that be what’s causing the behaviour you’re seeing?

**Comment by NelsonScott** [comment]
Went to the heroku dashboard and changed the Config Var HEROKU_URL to be that of my custom domain, no luck.  Still forwards the user to the heroku url.  Is there something else in the config to get ghost working on heroku that might be an issue?

**Comment by cobyism** [comment]
@NelsonScott Does changing the environment variable restart your application? If not, you may need to trigger your app to restart for Ghost to pick up the new `HEROKU_URL` value. If you’ve got the CNAME record pointing at Heroku as they require, the subdomain added to the app via the Heroku dashboard, and the `HEROKU_URL` environment variable configured, then that should be everything :confused:

**Comment by NelsonScott** [comment]
It works!  It could be the change to the HEROKU_URL took a little while to work, or maybe it was just a DNS propagation issue. Either way thanks for helping me figure this out.

**Comment by cobyism** [comment]
No worries. Glad to hear something sorted it out! :smiley:

**Comment by DefCon-007** [comment]
I am still facing this issue. Using `HEROKU_URL` environment variable was of no help.
