### ISSUE TITLE
S3 file uploads not working

### ISSUE THREAD

**Issue by nickmjones** [cobyism/ghost-on-heroku#38]
I _think_ I have S3 uploads set up correctly, but none of the files I try to add to posts finish uploading successfully. I'm getting an error in my browser console that says "Failed to load resource: the server responded with a status of 503 (Service Unavailable)" with a url of (myherokuapp.com) "/ghost/api/v0.1/uploads/"

Images never actually make it to the bucket, so I suppose there's could be something happening there. But the error seems like there's a misconfiguration inside the app. What am I missing here?

**Comment by cobyism** [comment]
I see you closed this just after opening it. Did you get this working?

**Comment by nickmjones** [comment]
@cobyism I did, sorry about that. I referred to #18 and that got me going. :+1:
