### ISSUE TITLE
Unable to upload

### ISSUE THREAD

**Issue by mitkodkn** [cobyism/ghost-on-heroku#39]
Everything on Amazon S3 is fine because I tested it with another application but when I try to upload something (like the blog cover or the blog logo), I get this error in the JavaScript console:

> Failed to load resource: the server responded with a status of 503 (Service Unavailable)
> https://name-of-my-app.herokuapp.com/ghost/api/v0.1/uploads/

**Comment by mitkodkn** [comment]
I'm sorry, the problem was in me. I updated the AWS user credentials and now it works fine.

**Comment by cobyism** [comment]
@mitkodkn Glad to hear you worked it out!
