### ISSUE TITLE
Build fails on new versions of Node by attempting to compile sqlite

### ISSUE THREAD

**Issue by leylandjacob** [cobyism/ghost-on-heroku#42]
The Node engine specified in package.json is 0.10.0, specifying a newer version like 4.1.1 causes the build to fail by attempting a compile of the sqlite module. I think this is related to https://github.com/cobyism/ghost-on-heroku/issues/15 and https://github.com/cobyism/ghost-on-heroku/issues/29

**Comment by holic** [comment]
Try one of the engines listed in Ghost's package.json? https://github.com/TryGhost/Ghost/blob/master/package.json#L25:L28

**Comment by holic** [comment]
Ghost recommends 0.10.x and supports 0.12.x. Closing for now, but feel free to open with more detailed information and after testing other Node versions!
