### ISSUE TITLE
custom domain name won't change

### ISSUE THREAD

**Issue by shakedlokits** [cobyism/ghost-on-heroku#47]
I've added my custom domain in the console, the 301 forward works fine but once in on the app the name changes back, I've changed my HEROKU_URL env but that didn't change a thing  :(

**Comment by holic** [comment]
What exactly did you set your `HEROKU_URL` to? How is your DNS configured?

**Comment by holic** [comment]
Closing for now due to inactivity. Feel free to re-open with more information

**Comment by jasan-s** [comment]
I am having the same problem, My heroku app url is https://myghostblog.herokuapp.com. I had set up a 301 redirect momentarily but for some reason when i enter my custom domain the 301 redirect keeps happening.  The cname has no effect

**Comment by jasan-s** [comment]
Setting HEROKU_URL with http://www.customdomain.com, clearing cache or trying in private tab did the trick.
