### ISSUE TITLE
Weird bug with word "final" after clean installation

### ISSUE THREAD

**Issue by calekennedy** [cobyism/ghost-on-heroku#49]
I just installed today, completely clean installation. I've never used ghost before and am looking forward to using it. I can replicate this bug on my macbook (chrome, safari), iphone (safari), and my windows 10 desktop (chrome). The bug is non-existent in the edge browser on win10. It happens both on the "post preview" view and once you navigate to the post.

----
In the "Welcome to Ghost" post, I noticed a bug in the following segment of text. 

Writing in Markdown is really easy. In the left hand panel of Ghost, you simply write as you normally would. Where appropriate, you can use *shortcuts* to **style** your content. For example, a list:

* Item number one
* Item number two
    * A nested item
* A final item

Specifically, the word "final" shows up as "inal". 

----

First off, let me say that all of these strings are being correctly written to the DOM. They are, however, being displayed incorrectly in the browser. I did some cursory tests and found that it's not exclusive this post either. I made a second post combining the letters "f" and "i" in various ways. Additionally, the casing of the letters matters. For instance, 

* "Fi"
* "FI" 
* "fI" 

all of these combinations are displayed correctly.

* "fi" --> "i"

is the first example of a combination displayed incorrectly.

* "ffi" will be displayed correctly.
* "ffii" will be displayed correctly.
* "fa" will be displayed correctly.

* "fii" will be displayed incorrectly. --> "ii"
* "ifi" will be displayed incorrectly. --> "ii"
* "Ffi" will be displayed incorrectly. --> "Fi"

I'm sure there are other combinations that are able to break, but I have no idea what would be 

A [live example](https://bug-demonstration.herokuapp.com/final-bug-demonstration/) can be found at that link.

If you would like access to  https://bug-demonstration.herokuapp.com/ghost/editor/2/ so you can drill into the examples for yourself, PM me for the login credentials. This is a demo site and as such it has no sensitive data.

**Comment by calekennedy** [comment]
UPDATE: 

I tried installing from https://ghost.org/download/ and the same problem occurs. 

You can close this issue if you think it should be in https://github.com/TryGhost/Ghost instead.

**Comment by holic** [comment]
@calekennedy I would definitely suggest submitting a bug upstream to the Ghost repo! Thanks!
