### ISSUE TITLE
Vendor Error on Setup 

### ISSUE THREAD

**Issue by DQvsRA** [cobyism/ghost-on-heroku#51]
Hi, Just take a look. It's a first time run.

![image](https://cloud.githubusercontent.com/assets/442111/12952224/ccf500fa-d026-11e5-855c-d83a39ecb86e.png)

Peace,
Vladimir Minkin

**Comment by cobyism** [comment]
Thanks for the issue, @DQvsRA. I’m having trouble reproducing this. Can you try deploy a second time?

**Comment by holic** [comment]
Closing for now. Feel free to re-open with steps to reproduce if you get the same error when trying to deploy again.
