### ISSUE TITLE
casper?

### ISSUE THREAD

**Issue by adamlynch11** [cobyism/ghost-on-heroku#53]
this may be a dumb question but why isn't Casper inside the themes directory?

**Comment by holic** [comment]
Casper is included as an npm dependency, then copied into the themes directory via a `postinstall` script (which runs after `npm install`). See [package.json](https://github.com/cobyism/ghost-on-heroku/blob/master/package.json).

**Comment by adamlynch11** [comment]
I meant locally.

so after I git cloned and git remote add origin and git pull origin master, my themes directory is still empty.

how might I remedy that?

appreciate your help.

**Comment by holic** [comment]
@adamlynch11 Running `npm install` should allow the theme to show up. Are you trying to make customizations to the theme?

**Comment by adamlynch11** [comment]
yes. I think my local isn't configured correctly. thanks.
