### ISSUE TITLE
NET::ERR_CERT_COMMON_NAME_INVALID

### ISSUE THREAD

**Issue by AlvaroR156** [cobyism/ghost-on-heroku#54]
I have followed all the steps to add the Custom Domain to Heroku #37 , but I get a "NET::ERR_CERT_COMMON_NAME_INVALID", you can see it on https://blog.lolagomezdebarros.es/
My local heroku app is: https://lolaghost.herokuapp.com/, which works fine. 
I haven't seen any thing like that in any of the other issues. Any suggestion?
Thanks for your time and great resource.

**Comment by AlvaroR156** [comment]
To add more info about my config:
HEROKU_URL: https://blog.lolagomezdebarros.es (I have also tried http://)
ALSO DOMAIN ADDED in Heroku:
![screen shot 2016-02-21 at 11 04 03](https://cloud.githubusercontent.com/assets/8481140/13202230/e078aa70-d88a-11e5-8751-dfb41227df51.png)

DNS: blog.lolagomezdebarros.es.	14400	IN	CNAME	lolaghost.herokuapp.com
AND DNS: www.blog.lolagomezdebarros.es.	14400	IN	CNAME	blog.lolagomezdebarros.es

I did the set up 24h ago, so any DNS propagation should already happened.

**Comment by holic** [comment]
It sounds like you don't have an SSL certificate set up for your custom domain. In order to do this with Heroku, you'll need to pay for their SSL addon ($20/mo I think). Alternatively, you can use Cloudflare DNS with their "Full" SSL setting turned on and it's free.

**Comment by holic** [comment]
Or, if you don't really need SSL, you should point your blog domain to `http://blog.lolagomezdebarros.es` to avoid it redirecting to https. That'll work as well.

**Comment by AlvaroR156** [comment]
Perfect!, I pointed to http://blog.lolagomezdebarros.es and everything works now.

**Comment by tonyjoker** [comment]
Sometimes, something just have happened on your computer and leads to this error. It's not just a fault from the server side or misconfigured.

I found this useful article, which may helped [to resolve your connection is not private error](https://usefulpcguide.com/16666/your-connection-is-not-private/). Check it out!
