### ISSUE TITLE
How can I access the "core" folder

### ISSUE THREAD

**Issue by Dorgam** [cobyism/ghost-on-heroku#55]
Hello,

In the past, I have been using Ghost with DigitalOcean and I had access to the "core" folder. It had two files that interested me to change the language of the blog into Arabic. A CSS file and moment.js file.

Now I am moving to heroku and after I clone I seem to not find the folder and not even casper theme folder. I looked into the .gitignore file and made it empty and committed my work and tried to re-clone again. Still I don't get the core folder nor the casper.

Can you please help me?
Thank you.

**Comment by holic** [comment]
In that case, ghost-on-heroku may not be for you. You may want to clone the actual Ghost repo (https://github.com/TryGhost/Ghost), add the Casper theme yourself, make the necessary customizations, and push to Heroku.
