### ISSUE TITLE
editing HEROKU_URL to our-url.com/foo doesn't work

### ISSUE THREAD

**Issue by adamlynch11** [cobyism/ghost-on-heroku#57]
Is this not possible? We'd like to run ghost on a subdirectory basically and according to this 

https://www.allaboutghost.com/how-to-install-ghost-in-a-subdirectory/

we just need to change the config.js to refer to the new path.

the config.js in this project already has that value specified as HEROKU_URL. Hooray!

But when I edit the variable to https://our-url.com/cms it doesn't seem to work.

Am I doing something wrong or is this not possible with this implementation?

**Comment by holic** [comment]
This project is targeted at folks looking to get Ghost up and running on a domain quickly. It doesn't really support specific/custom installations, like running from a directory.

Where is the rest of your site running? If it's already a Node.js app on Heroku, you could add Ghost as a dependency to your project and mount it to the desired path (e.g `/cms`). If it's not a Node.js app or not running on Heroku, you'll likely need to proxy requests from `/cms` to wherever it is running.

Alternatively, you could install this app to a subdomain (e.g. `cms.your-url.com`) and set your `HEROKU_URL` to that.

**Comment by adamlynch11** [comment]
thanks @holic 

the rest of the site is a Rails app running on Heroku, we were going to have a small piece in the rack middleware that listened for any request to ``/cms`` and get it from this app instead.

the subdomain approach would totally work but then the published URLs would be weird/non optimal (we're wanting to use ghost as a CMS for our presale/non-authed content.)

thanks very much for your quick response. any other ideas how we could refer to this implementation from a Rails app on Heroku?

**Comment by holic** [comment]
@adamlynch11 Do you have an example of how you're proxying requests?

**Comment by adamlynch11** [comment]
meaning how we would do it? yes, I can provide that tomorrow.

also trying to figure out how this plays in http://stackoverflow.com/questions/28133512/running-ghost-module-for-node-js-on-heroku-as-subdirectory

It's weird, from what I can tell, it seems like just changing the HEROKU_URL should work.

Does something need to be tweaked near line 51 (paths) in config.js?

**Comment by holic** [comment]
I would need to see concrete examples of how you would be proxying requests before I can answer specifically how it'd work.

**Comment by marktabler** [comment]
@holic @adamlynch11 This is essentially how we plan to proxy these requests:  https://gist.github.com/marktabler/120a2150065781f1e642

I don't think we'll have a problem mapping to any subdomain or subdirectory, and I don't think we'll have a problem mapping to `/`.  

The only thing this really hinges on is being able to tell by the request URI whether or not to hand responsibility over to the CMS; so far, that's not been a big problem either.

**Comment by cancan101** [comment]
Was there ever a resolution to having the ghost app serve on a subdomian? I plan to run a reverse proxy elsewhere to stich together my site along with a /blog subdomain. Ideally can have upstream for blog just be the heroku app.
