### ISSUE TITLE
Redirect loop on heroku

### ISSUE THREAD

**Issue by e911miri** [cobyism/ghost-on-heroku#58]
Hi there, 
I setup ghost on heroku and I have my heroku url working at https://tomiwaxyz.herokuapp.com

I have also setup a custom domain in heroku to https://tomiwa.xyz
That means I needed to update my Ghost heroku url to https://tomiwa.xyz
The root for https://tomiwa.xyz is pointed to https://tomiwaxyz.herokuapp.com using cloudflare

The result is a redirect loop, is there something I am not doing right?

**Comment by holic** [comment]
Can you post your DNS settings and your Ghost domain settings?

**Comment by e911miri** [comment]
Hi @holic, thanks for looking into this. My heroku settings is contained in the first two screen shots, while the third is my cloudflare settings
<img width="810" alt="screen shot 2016-03-09 at 8 24 44 am" src="https://cloud.githubusercontent.com/assets/710643/13670620/48cf1804-e6cb-11e5-91c0-a0f6f1b53cd3.png">
<img width="798" alt="screen shot 2016-03-09 at 8 25 27 am" src="https://cloud.githubusercontent.com/assets/710643/13670621/48d1e142-e6cb-11e5-8aa9-a71d2734b378.png">
<img width="1021" alt="screen shot 2016-03-10 at 2 19 40 pm" src="https://cloud.githubusercontent.com/assets/710643/13670623/48e12738-e6cb-11e5-9243-151304b4494d.png">

**Comment by holic** [comment]
@e911miri And what about the output of your `heroku domains` command? And what type of Cloudflare SSL setting have you turned on (e.g. Flexible, Full, Strict)?

**Comment by holic** [comment]
Closing due to lack of reply - assuming resolved or no longer a priority. Feel free to provide more information and I can try to help debug.

**Comment by bencooper222** [comment]
I'm having the exact same issue. My settings match @e911miri. The output for heroku domains is the following: 
![image](https://user-images.githubusercontent.com/9143563/35018827-2385e7f6-fae9-11e7-902f-6577badefa71.png)

Cloudflare SSL is on free and this is on a free dyno.

**Comment by holic** [comment]
@bencooper222 Are you using "Full" for your SSL setting in Cloudflare? Can you screenshot your DNS and SSL settings in Cloudflare?

**Comment by ifvictr** [comment]
@bencooper222 Also ran into this error, though I solved it by changing `https` to `http` in the `PUBLIC_URL` variable.

**Comment by bencooper222** [comment]
@ifvictr 's fix worked for me. It won't let me access `<custom domain>/ghost` but `<app name>.herokuapp.com/ghost` works so that's a minor quibble.

**Comment by andreierdoss** [comment]
Besides setting the `PUBLIC_URL` I also set a Page Rule in Cloudflare that would assure SSL. `http://*domain.com/*` with `Always use HTTPS`

**Comment by wyattbenno777** [comment]
Did the same fix. But members.js tries to fetch from http rather than https causing an error. Anyone figure out a way to fix that?
