### ISSUE TITLE
Heroku repo is empty

### ISSUE THREAD

**Issue by alexzaitsev** [cobyism/ghost-on-heroku#62]
Firstly I'm sorry if this is my bad.
I started my blog with this handy tool but after that I wanted to change some code. 
So I cloned heroku repo with command `heroku git:clone -a appname` as it's suggested in heroku docs. 
What was my wondering when git told me `warning: You appear to have cloned an empty repository.`
Maybe you have some ideas? Would be great. Thanks a lot.

**Comment by alexzaitsev** [comment]
I think it can be this issue http://stackoverflow.com/questions/18751063/trying-to-heroku-gitclone-after-heroku-fork-yields-an-empty-repository
If I just clone this repository and use it as my source - will it work?

**Comment by alexzaitsev** [comment]
Not your bug.

**Comment by pratap234337** [comment]
Alex, did you find any solution for this ?
I'm having this same problem

**Comment by alexzaitsev** [comment]
@pratap234337 yeap. 
**Don't use `Deploy to Heroku` button.** 
Just fork this repo, modify files if it is needed and push to Heroku.

**Comment by amigolargo** [comment]
This worked for me: http://stackoverflow.com/questions/13804885/heroku-gitclone-creates-empty-repository#answer-41379481
