### ISSUE TITLE
Any plans to support Google Cloud Storage? 

### ISSUE THREAD

**Issue by niranjan92** [cobyism/ghost-on-heroku#64]
In recent times, Google cloud storage has emerged as a strong and price competitive option to AWS. Is there any way I can link my google cloud storage bucket instead of S3?

**Comment by cobyism** [comment]
I’m sure there is a way, but I’m not currently up to speed on the easiest method to integrate something like Google Cloud Storage with Ghost as deployed to Heroku. If you get it working, and there’s a way of doing it that doesn’t make the documentation (and the Heroku deployment form/screen) overwhelming and confusing, then I’d be open to considering a pull request to add it 😃.

Currently though, I have no plans to explore adding that functionality, so I’m going to close this issue out.

**Comment by bencooper222** [comment]
I might make a PR to integrate this plugin: https://www.npmjs.com/package/ghost-google-cloud-storage
