### ISSUE TITLE
git:clone says my repo is empty

### ISSUE THREAD

**Issue by conor909** [cobyism/ghost-on-heroku#67]
My app is up and running on heroku just fine, but when I try to download it locally using
`heroku git:clone --app MYAPPNAME`

Its creates the folder and the git init, but it's an empty folder and in the console:
`warning: You appear to have cloned an empty repository.`

And when using a client to create a new repo locally it complains about not having a master branch:
`fatal: Couldn't find remote ref master`

**Comment by conor909** [comment]
From Heroku support:

Recent changes are such that `heroku git:clone` is only useful for applications that are deployed with Heroku's hosted git service. In effect this means that applications deployed via GitHub, DropBox or "Deploy to Heroku" buttons will result in an empty repo when cloned.

In that case, you'll need to download the source repository and add the heroku remote to that repo. Once you've done that you can push with git (`git push heroku master`) and you'll be able to clone the repo after that.

**Comment by holic** [comment]
Ooof... that sounds like a pretty terrible experience. I wonder if manually adding the remote and pulling it down works? 

Closing this as it's unrelated to ghost-on-heroku but a general Heroku issue.
