### ISSUE TITLE
Access Denied on image upload

### ISSUE THREAD

**Issue by Dreyfuzz** [cobyism/ghost-on-heroku#70]
Ran through two setups and I can't figure out where it's gone wrong. Set up a new bucket and new IAM user (no groups or permissions attached). Included all config vars correctly, as far as I can tell. Here is the bucket policy:

```
{
	"Id": "Policy1465054892694",
	"Version": "2012-10-17",
	"Statement": [
		{
			"Sid": "Stmt1465054801755",
			"Action": [
				"s3:ListBucket"
			],
			"Effect": "Allow",
			"Resource": "arn:aws:s3:::<bucketname>",
			"Principal": {
				"AWS": [
					"arn:aws:iam::<awsID>:user/<iamusername>"
				]
			}
		},
		{
			"Sid": "Stmt1465054845550",
			"Action": [
				"s3:DeleteObject",
				"s3:GetObject",
				"s3:PutObject"
			],
			"Effect": "Allow",
			"Resource": "arn:aws:s3:::<bucketname>/*",
			"Principal": {
				"AWS": [
					"arn:aws:iam::363628483589:user/<iamusername>"
				]
			}
		},
		{
			"Sid": "Stmt1465054887900",
			"Action": [
				"s3:GetObject"
			],
			"Effect": "Allow",
			"Resource": "arn:aws:s3:::<bucketname>/*",
			"Principal": "*"
		}
	]
}
```

I even tried adding a grantee of "Everyone" to the bucket with access, but still got Access Denied. Here's a log record:

`27f33dcde6266001f37a6e5328c7c6343419b6ea6acb1310e176d2af426c959f <bucketname> [04/Jun/2016:01:45:57 +0000] 54.163.103.165 arn:aws:iam::<awsID>:user/<iamuser> DA10333234650546 REST.PUT.OBJECT 2016/Jun/1424443_174755136058674_264701358_n-1465004757600.png "PUT /2016/Jun/1424443_174755136058674_264701358_n-1465004757600.png HTTP/1.1" 403 AccessDenied 243 13308 24 - "-" "aws-sdk-nodejs/2.3.17 linux/v0.10.45" -`

**Comment by Dreyfuzz** [comment]
@icaruswings You got it, I had to learn to write IAM user policies. Sorry for not returning to document.

**Comment by holic** [comment]
Sounds like this has been resolved. Thanks for posting the solution!

**Comment by joallard** [comment]
@icaruswings You just saved me another hour of suffering in this dumpster fire that is the AWS UX. Turns out AWS publishes read-write policies without the Acl ones. (I figure that's what happens when you force your users to use overcomplicated tools they can mess up with)
