### ISSUE TITLE
Upgrade Node to 4.2 & memory management?

### ISSUE THREAD

**Issue by jvrsgsty** [cobyism/ghost-on-heroku#75]
Having deployed Ghost 0.9.0 successfully to Heroku in the past, I noticed your `package.json` node version does not match the current recommendation for running Ghost 0.9.0 [here](http://support.ghost.org/supported-node-versions/). 
I am a total beginner to Node, but I am unsure if this would cause an issue when launching the Ghost server? I mean, I'm guessing Ghost server would not be running on the 4.2+ version of node, would it?

Anyways, after upgrading my own blog to Ghost 0.9.0 and Node 4.2+, I noticed a bunch of R14 Memory errors on the Heroku metrics console for my blog app. These errors cause my dyno to use swap space, making response time a bit slower and causing ocassional restarts of the app. Turns out Garbage Collection is a bit lazy in Node 4.2 +, as disscussed [here](https://github.com/nodejs/node/issues/3370). 

The discussion leads to a solution of this problem with [this package](https://github.com/damianmr/heroku-node-settings), but I was unable to make it work swiftly on my installation. Essentially it is just a bash script to query the amount of memory allocated to your dyno, which then adjusts three memory usage flags you can pass to node to avoid this error. I ended up setting up the flags directly on the call to `node` on the `start` command of Ghost's own `package.json`. Dirty, dirty, and hardcoded to match my current dyno size. 

Perhaps we can take both the upgrade to Node 4.2+ and the memory management issue into consideration? I'd be glad to help.

**Comment by holic** [comment]
I'd love to upgrade the default Node version but the memory issue is a little distressing. Happy to accept a PR for this change, including use of heroku-node-settings.

To clarify, you swapped out the `node` bit of the `start` script in `package.json` with `heroku-node-settings`, but you weren't able to get it to run properly?

**Comment by jvrsgsty** [comment]
Exactly. Just like the `Readme` on the `heroku-node-settings` repo states... That was on Ghost's `package.json`, though. If your package works as I am guessing (again, total beginner to Node here), just swapping it out in your `package.json` should suffice. I'll look into the issue of it not working out for me and get back to you. It had something to do with the `heroku-node-settings` script not being found in the path.  

I have been monitoring my own blog's memory usage with the hard coded flags, and they have now been quite stable and below Heroku's limits.

**Comment by aorcsik** [comment]
I managed to add https://github.com/damianmr/heroku-node-settings as a dependency (it has an npm module). After that, just replaced `node` with `heroku-node-settings` in the start script and everything worked. I also added `~4.2` as node engine to `package.json`.

**Comment by jvrsgsty** [comment]
It appears the memory leak issue is solved on Ghost 0.10.1 as released in their dev blog. 
https://dev.ghost.org/ghost-0-10-1/
Haven't tested it out, though...
