### ISSUE TITLE
Issue during Heroku Build

### ISSUE THREAD

**Issue by jaspersone** [cobyism/ghost-on-heroku#79]
Tried deploying to Heroku using the one click deploy. Here is the following log from Heroku:

`/tmp/build_dadeff5abd5dc88602a0c2bd31d52b42/cobyism-ghost-on-heroku-2581f67
       > ncp node_modules/Casper content/themes/casper
       
       There were errors during the copy.
       Error: ENOENT, lstat '/tmp/build_dadeff5abd5dc88602a0c2bd31d52b42/cobyism-ghost-on-heroku-2581f67/node_modules/Casper'
       
       npm ERR! Linux 3.13.0-95-generic
       npm ERR! argv "/tmp/build_dadeff5abd5dc88602a0c2bd31d52b42/cobyism-ghost-on-heroku-2581f67/.heroku/node/bin/node" "/tmp/build_dadeff5abd5dc88602a0c2bd31d52b42/cobyism-ghost-on-heroku-2581f67/.heroku/node/bin/npm" "install" "--unsafe-perm" "--userconfig" "/tmp/build_dadeff5abd5dc88602a0c2bd31d52b42/cobyism-ghost-on-heroku-2581f67/.npmrc"
       npm ERR! node v0.10.47
       npm ERR! npm  v2.15.1
       npm ERR! code ELIFECYCLE
       npm ERR! ghost-on-heroku@0.11.2 postinstall: `ncp node_modules/Casper content/themes/casper`
       npm ERR! Exit status 1
       npm ERR!
       npm ERR! Failed at the ghost-on-heroku@0.11.2 postinstall script 'ncp node_modules/Casper content/themes/casper'.
       npm ERR! This is most likely a problem with the ghost-on-heroku package,
       npm ERR! not with npm itself.
       npm ERR! Tell the author that this fails on your system:
       npm ERR!     ncp node_modules/Casper content/themes/casper
       npm ERR! You can get information on how to open an issue for this project with:
       npm ERR!     npm bugs ghost-on-heroku
       npm ERR! Or if that isn't available, you can get their info via:
       npm ERR!
       npm ERR!     npm owner ls ghost-on-heroku
       npm ERR! There is likely additional logging output above.
       
       npm ERR! Please include the following file with any support request:
       npm ERR!     /tmp/build_dadeff5abd5dc88602a0c2bd31d52b42/cobyism-ghost-on-heroku-2581f67/npm-debug.log
-----> Build failed`

**Comment by joshuaguild** [comment]
I'm running into the same issue. Hopefully this can get fixed quickly because it's a great idea!

**Comment by AaronM04** [comment]
@jaspersone were you using Linux? Because linux has a case-sensitive filesystem (unlike OS X, which is presumably what most users are using). I think you need to replace "node_modules/Casper" with "node_modules/casper".

**Comment by jaspersone** [comment]
thanks @AaronM04 that gets the system building
