### ISSUE TITLE
Image Upload Error ghost-s3 Not Configured

### ISSUE THREAD

**Issue by EnFlight** [cobyism/ghost-on-heroku#83]
Is anyone else receiving ERROR: ghost-s3 is not configured when trying to add an image?

I copied the repo and pushed it to heroku. Everything else seems to work except for S3 uploads. 

Should storage/ghost-s3 be updated to storage/ghost-s3-storage-adapter to reflect the new dependency in package.json?

**Comment by kevin-stripe** [comment]
This should already be happening: https://github.com/cobyism/ghost-on-heroku/blob/master/content/storage/ghost-s3/index.js

**Comment by holic** [comment]
This should already be happening: https://github.com/cobyism/ghost-on-heroku/blob/master/content/storage/ghost-s3/index.js

**Comment by EnFlight** [comment]
Hi @holic thank you for the response.

I have that set up correctly https://github.com/EnFlight/enflight.design/blob/master/content/storage/ghost-s3/index.js

I did not change anything when I downloaded the files and pushed to heroku. Is there a step I might've missed that affects how images are uploaded to S3?

I keep getting ERROR: ghost-s3 when I check heroku logs and the image before when I try to upload on editor.

![screen shot 2016-11-02 at 1 57 06 pm](https://cloud.githubusercontent.com/assets/9838591/19976109/cbea7428-a231-11e6-8b27-4d531fd1fb2b.png)

**Comment by EnFlight** [comment]
I figured out the issue.

I had to add S3_BUCKET_REGION to my config variables on heroku. It wasn't necessary on the older version of ghost I was running, but is on 0.11. 

It's a lesson for me to read the readme...

Thank you for the help.
