### ISSUE TITLE
Problemas con la permanencia de archivos.

### ISSUE THREAD

**Issue by ghost** [cobyism/ghost-on-heroku#86]
Cuando subo un tema en la carpeta de temas y reinicio el "Dyno" el tema no hacia efecto el area de administración de ghost; la carpeta que uso es esta: `MYAPP/content/themes`

También intente instalarlo desde el navegador (area de administración) pero el problema persiste, no se cual sea el problema. espero que me ayuden. gracias.

**Comment by WaqasIbrahim** [comment]
Hello, Can you share `package.json` file inside the theme folder? Thanks

**Comment by nniiccoollaa55** [comment]
`{
  "name": "ghost-on-heroku",
  "description": "Just a blogging platform on Heroku.",
  "license": "MIT",
  "repository": {
    "type": "git",
    "url": "git://github.com/cobyism/ghost-on-heroku.git"
  },
  "bugs": "https://github.com/TryGhost/Ghost/issues",
  "private": true,
  "version": "0.11.2",
  "dependencies": {
    "casper": "TryGhost/Casper#1.3.3",
    "ghost": "0.11.2",
    "ghost-s3-storage-adapter": "3.0.4",
    "ncp": "^2.0.0",
    "pg": "latest"
  },
  "engines": {
    "node": "~0.10.0"
  },
  "scripts": {
    "postinstall": "ncp node_modules/casper content/themes/casper",
    "start": "node server.js"
  }
}
`

**Comment by nicolasrodriguezq** [comment]
Me pasa lo mismo.

**Comment by WaqasIbrahim** [comment]
Did you check heroku logs? Are there any errors in heroku logs when you restart the dyno?

**Comment by fega** [comment]
Heroku tiene un sistema de archivos efímero, lo cual quiere decir que los cambios son borrados unos minutos después de ser creados. debido a que los temas se "intentan guardar" dentro de heroku, son borrados o denegados.

En teoría lo que debes hacer es clonar el repo con algo así como

heroku git:clone --app YOURAPPNAME

y copiar tu tema en la carpeta content/themes.

En mi caso estoy teniendo clonando el repo y me dice que esta vació... 

inténtalo y me dices.

**Comment by cobyism** [comment]
Thanks for jumping in with an explanation there, @fega. 🙏🏻

Closing as the OP is now (wait for it)… a ghost! 😎
