### ISSUE TITLE
Image no show

### ISSUE THREAD

**Issue by kul1** [cobyism/ghost-on-heroku#89]
The image attached is no show. I checked with s3 the files already there. 
Check with browser inspect or copy paste the content look ok for me but the app just not display image. Don't know what missing

![screen shot 2559-12-10 at 3 02 21 am](https://cloud.githubusercontent.com/assets/3953832/21062909/9c51d3bc-be85-11e6-905a-43476aa47a5f.png)
![screen shot 2559-12-10 at 3 02 41 am](https://cloud.githubusercontent.com/assets/3953832/21062915/a00f59ac-be85-11e6-8953-a08bf61d2e63.png)
![screen shot 2559-12-10 at 3 02 58 am](https://cloud.githubusercontent.com/assets/3953832/21062918/a709a546-be85-11e6-9290-97016f6720aa.png)

**Comment by cobyism** [comment]
This will almost certainly be an issue with the way the S3 bucket’s access policy has been configured, rather than any issue with this codebase. There‘s been a few other issues reported on this repository in the past, perhaps looking through some of the closed issues might help you find an answer?
