### ISSUE TITLE
Ghost v1.0 will drop postgresql support

### ISSUE THREAD

**Issue by legendtang** [cobyism/ghost-on-heroku#91]
Check this https://dev.ghost.org/dropping-support-for-postgresql/

**Comment by holic** [comment]
Oof, this is not great news.

@cobyism What do you think we should do here? The free MySQL offerings on Heroku would be great for trying out Ghost, but I imagine folks would quickly need to upgrade (5MB storage cap on free plans).

**Comment by cobyism** [comment]
I’d rather keep this repo inline with what’s supported officially by Ghost, so unless support for postgresql emerges from the ghost community, I think switching to the free MySQL offerings is the best way to move forward.

**Comment by nodesocket** [comment]
I wanted to come and comment on this. All the MySQL Heroku providers offer a very limited free tier. For example, ClearDB only offers a 5MB MySQL database on their free plan. Will ghost even work with 5MB?

What are options?

**Comment by diervo** [comment]
After a bunch of trial and error and debugging, I was able to successfully make a deployment to heroku with `ghost 1.5.0` with ClearDB. Right now with the default schema and 5 small posts I still in 0.73mb, so this should not be a blocker towards 1.x

**Comment by legendtang** [comment]
@diervo I suggest to provide advice on migration in readme if you've come up with one :)

**Comment by trevorwhealy** [comment]
@diervo if you'd provide a fork of this repo I'd use it 👍

**Comment by diervo** [comment]
Will try to put something together over the weekend if I have time.

**Comment by mars** [comment]
See PR for Ghost 1.x: https://github.com/cobyism/ghost-on-heroku/pull/119

That ones is using JawsDB. I'm sure ClearDB would work too.

**Comment by cobyism** [comment]
#119 has been merged in, so I’m going to close this out.
