### ISSUE TITLE
Themes Save Location

### ISSUE THREAD

**Issue by joshlemon** [cobyism/ghost-on-heroku#94]
Where is this App actually saving the Themes when you import then via the Admin page?

**Comment by cobyism** [comment]
@joshlemon Unfortunately, this repository is purely focused on the process of deploying Ghost to Heroku. For questions and support relating to the behaviour and function of Ghost itself, please check [the official support page](http://support.ghost.org/), or [the official issue tracker](https://github.com/TryGhost/Ghost/issues).
