### ISSUE TITLE
Support for Node version 0.12.x no longer supported

### ISSUE THREAD

**Issue by weactivist** [cobyism/ghost-on-heroku#95]
According to the docs Node 0.12.x is no longer supported. When I try to upgrade Ghost version from 0.11.3 to 0.11.4 I get an error "Unsupported version of Node".

http://support.ghost.org/supported-node-versions/

>Support for 0.12.x will also be dropped on 31st December 2016.

remote: -----> Building dependencies
remote:        Installing node modules (package.json)
remote:        
remote:        > ghost@0.11.4 preinstall /tmp/build_d1fa551a089427e731c872676428e882/node_modules/ghost
remote:        > node core/server/utils/npm/preinstall.js
remote:        
remote:        ERROR: Unsupported version of Node
remote:        Ghost supports LTS Node versions: ^4.2.0 || ^6.9.0
remote:        You are currently using version: 0.12.18
remote:        This check can be overridden, see http://support.ghost.org/supported-node-versions/ for more info
remote:        npm ERR! Linux 3.13.0-105-generic
remote:        npm ERR! argv "/tmp/build_d1fa551a089427e731c872676428e882/.heroku/node/bin/node" "/tmp/build_d1fa551a089427e731c872676428e882/.heroku/node/bin/npm" "install" "--unsafe-perm" "--userconfig" "/tmp/build_d1fa551a089427e731c872676428e882/.npmrc"
remote:        npm ERR! node v0.12.18
remote:        npm ERR! npm  v2.15.11
remote:        npm ERR! code ELIFECYCLE
remote:        
remote:        npm ERR! ghost@0.11.4 preinstall: `node core/server/utils/npm/preinstall.js`
remote:        npm ERR! Exit status 231
remote:        npm ERR!
remote:        npm ERR! Failed at the ghost@0.11.4 preinstall script 'node core/server/utils/npm/preinstall.js'.
remote:        npm ERR! This is most likely a problem with the ghost package,
remote:        npm ERR! not with npm itself.
remote:        npm ERR! Tell the author that this fails on your system:
remote:        npm ERR!     node core/server/utils/npm/preinstall.js
remote:        npm ERR! You can get information on how to open an issue for this project with:
remote:        npm ERR!     npm bugs ghost
remote:        npm ERR! Or if that isn't available, you can get their info via:
remote:        npm ERR!
remote:        npm ERR!     npm owner ls ghost
remote:        npm ERR! There is likely additional logging output above.
remote:        
remote:        npm ERR! Please include the following file with any support request:
remote:        npm ERR!     /tmp/build_d1fa551a089427e731c872676428e882/npm-debug.log
remote: 
remote: -----> Build failed
remote:        
remote:        We're sorry this build is failing! You can troubleshoot common issues here:
remote:        https://devcenter.heroku.com/articles/troubleshooting-node-deploys
remote:        
remote:        If you're stuck, please submit a ticket so we can help:
remote:        https://help.heroku.com/
remote:        
remote:        Love,
remote:        Heroku
remote:        
remote:  !     Push rejected, failed to compile Node.js app.
remote: 
remote:  !     Push failed
remote: Verifying deploy...
remote: 
remote: !       Push rejected to sheerio.
remote: 
To https://git.heroku.com/sheerio.git
 ! [remote rejected] master -> master (pre-receive hook declined)
error: failed to push some refs to 'https://git.heroku.com/sheerio.git'

**Comment by weactivist** [comment]
#96 
I've made a PR on this which is pretty well untested. The only thing I've done is to do the upgrades of version and tested a deploy to Heroku, which passed.

**Comment by nodesocket** [comment]
👍 . Let's merge
