### ISSUE TITLE
Themes not staying saved

### ISSUE THREAD

**Issue by noahprince22** [cobyism/ghost-on-heroku#97]
After I upload a theme in the admin panel, it seems to work for a few minutes.

When I come back later in the day, I get a 500 error telling me the theme is missing. When I go to the admin panel, the theme is no longer there.

**Comment by VA7NFH** [comment]
I had the same issue,
It's because your telling it not to use file storage. 
The way to fix it is to clone it locally and then put the theme in the themes folder and push, then select it from the admin panel and save.

**Comment by fega** [comment]
When I try to clone, git saids that is an empty repo :/

**Comment by VA7NFH** [comment]
Take a look at #67

**Comment by WaqasIbrahim** [comment]
@VA7NFH thanks for the solution.

**Comment by boxedpaul** [comment]
I now this ticket is old, but...

> ...then put the theme in the themes folder and push, then select it from the admin panel and save.

The new theme file should not be zipped. Thought it might be worth mentioning as I spent some time before I realised this.
